name: Build and Test Vortex

on:
  pull_request:
    branches: [main, test]
  push:
    branches: [main, test]
  schedule:
    - cron: '*/5 * * * *'

jobs:  
  build-vortex:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v4
    - name: Run batch file
      run: cd miscs/apptainer && chmod +x run-crnch-vortex.sh && sbatch run-crnch-vortex.sh

