name: Build and Test Vortex

on:
  pull_request:
    branches: [main, test]
  push:
    branches: [main, test]
  schedule:
    - cron: '*/5 * * * *'

jobs:  
  build-vortex:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v4
    - name: Run batch file
<<<<<<< HEAD
      run: cd miscs/apptainer && chmod +x run-crnch-vortex.sh && sbatch run-crnch-vortex.sh
=======
      run: cd miscs/apptainer && hostname && pwd && chmod +x run_apptainer.sh && sbatch run_apptainer.sh
>>>>>>> 7ba3f1173328a62511881863548f2a56db1a2d8b
      
